name: Build and upload

on: workflow_dispatch

jobs:
  build:
    name: Build and upload

    strategy:
      matrix:
        platform:
          - { name: 'Linux'    ,os: ubuntu-22.04 ,shell: 'bash'                }
          # - { name: 'Mac'      ,os: macos-12     ,shell: 'bash'                }
          # - { name: 'Mac (M1)' ,os: macos-12     ,shell: 'bash'      ,m1: true }
          - { name: 'Windows'  ,os: windows-2022 ,shell: 'msys2 {0}'           }

    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    steps:
      - uses: actions/checkout@v3

      - if: ${{ startsWith(matrix.platform.os, 'ubuntu-') }}
        run: npm run install-deps-ubuntu

      - if: ${{ startsWith(matrix.platform.os, 'macos-') }}
        run: npm run install-deps-mac

      - if: ${{ matrix.platform.m1 }}
        run: echo "M1=1" >> $GITHUB_ENV

      - if: ${{ startsWith(matrix.platform.os, 'windows-') }}
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          path-type: inherit
          install: >-
            mingw-w64-x86_64-cc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkg-config
      - if: ${{ startsWith(matrix.platform.os, 'windows-') }}
      - run: |
          echo 'PATH="${PATH}:/c/Program Files/nodejs/"' >> /etc/profile
          echo 'export PATH' >> /etc/profile

      - run: |
          npm install zx
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run publish
