name: Build and upload

on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build and upload

    strategy:
      matrix:
        platform:
          - { name: 'Linux', os: ubuntu-latest }
          - { name: 'Mac', os: macos-latest }
          - { name: 'Mac (M1)', os: macos-latest, m1: true }
          - { name: 'Windows', os: windows-latest }

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v2

      - if: ${{ startsWith(matrix.platform.os, 'ubuntu-') }}
        run: |
          sudo apt-get update
          sudo apt-get install build-essential git make autoconf automake libtool \
              pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
              libaudio-dev libjack-dev libsndio-dev libsamplerate0-dev libx11-dev libxext-dev \
              libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libwayland-dev \
              libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
              libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev \
              libpipewire-0.3-dev libdecor-0-dev

      - if: ${{ startsWith(matrix.platform.os, 'macos-') }}
        run: "brew install ninja"

      - if: ${{ matrix.platform.m1 }}
        run: "# TODO crosscompile"

      - if: ${{ startsWith(matrix.platform.os, 'windows-') }}
        run: ""

      - run: |
          npm install
          npm run publish
          npx prebuild --upload-all ${{ secrets.GITHUB_TOKEN }}
