name: Build and upload

on: workflow_dispatch

jobs:
  build:
    name: ${{ matrix.platform.name }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: 'Linux (x64)'   ,os: ubuntu-22.04              }
          - { name: 'Windows (x64)' ,os: windows-2022              }
          - { name: 'Mac (x64)'     ,os: macos-12                  }
          - { name: 'Mac (arm64)'   ,os: macos-12     ,arch: arm64 }

    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: 'bash'

    steps:
      - uses: actions/checkout@v3

      - if: ${{ startsWith(matrix.platform.os, 'ubuntu-') }}
        run: npm run install-deps-ubuntu

      - if: ${{ startsWith(matrix.platform.os, 'macos-') }}
        run: npm run install-deps-mac

      - if: ${{ matrix.platform.arch }}
        run: echo "CROSS_COMPILE_ARCH=${{ matrix.platform.arch }}" >> $GITHUB_ENV

      # - if: ${{ startsWith(matrix.platform.os, 'windows-') }}
      #   uses: msys2/setup-msys2@v2
      #   with:
      #     msystem: mingw64
      #     install: >-
      #       mingw-w64-x86_64-cc
      #       mingw-w64-x86_64-make
      #       mingw-w64-x86_64-cmake
      # - if: ${{ startsWith(matrix.platform.os, 'windows-') }}
      #   run: |
      #     echo 'PATH="${PATH}:/c/Program Files/nodejs/"' >> /etc/profile
      #     echo 'export PATH' >> /etc/profile

      - run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run release
