name: Build and upload

on: workflow_dispatch

jobs:
  build:
    name: ${{ matrix.platform.name }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: 'Linux (x64)'   ,os: ubuntu-22.04              }
          - { name: 'Windows (x64)' ,os: windows-2022              }
          - { name: 'Mac (x64)'     ,os: macos-12                  }
          - { name: 'Mac (arm64)'   ,os: macos-12     ,arch: arm64 }

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v3

      - if: ${{ startsWith(matrix.platform.os, 'ubuntu-') }}
        run: npm run install-deps-ubuntu

      - if: ${{ startsWith(matrix.platform.os, 'macos-') }}
        run: npm run install-deps-mac

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROSS_COMPILE_ARCH: ${{ matrix.platform.arch }}
        run: npm run release
