name: Build and upload

on: workflow_dispatch

jobs:
  build:
    name: Build and upload

    strategy:
      matrix:
        platform:
          # - { name: 'Linux'       ,os: ubuntu-22.04 ,shell: 'bash'                }
          - { name: 'Mac    '     ,os: macos-12     ,shell: 'bash'                }
          - { name: 'Mac (arm64)' ,os: macos-12     ,shell: 'bash'      ,m1: true }
          # - { name: 'Windows'     ,os: windows-2022 ,shell: 'msys2 {0}'           }

    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    steps:
      - uses: actions/checkout@v3

      - if: ${{ startsWith(matrix.platform.os, 'ubuntu-') }}
        run: npm run install-deps-ubuntu

      - if: ${{ startsWith(matrix.platform.os, 'macos-') }}
        run: npm run install-deps-mac

      - if: ${{ matrix.platform.m1 }}
        run: echo "CROSS_COMPILE_ARCH=arm64" >> $GITHUB_ENV

      - if: ${{ startsWith(matrix.platform.os, 'windows-') }}
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            cmake
            mingw-w64-x86_64-cc
      - if: ${{ startsWith(matrix.platform.os, 'windows-') }}
        run: |
          echo 'PATH="${PATH}:/c/Program Files/nodejs/"' >> /etc/profile
          echo 'export PATH' >> /etc/profile

      - run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run release
