name: Build and upload

on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build and upload

    strategy:
      matrix:
        platform:
          - { name: 'Linux'    ,os: ubuntu-22.04           }
          - { name: 'Mac'      ,os: macos-12               }
          - { name: 'Mac (M1)' ,os: macos-12     ,m1: true }
          - { name: 'Windows'  ,os: windows-2022           }

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v3

      - if: ${{ startsWith(matrix.platform.os, 'ubuntu-') }}
        run: npm run install-deps-ubuntu

      - if: ${{ startsWith(matrix.platform.os, 'macos-') }}
        run: npm run install-deps-mac

      # - if: ${{ matrix.platform.m1 }}
      #   run: "# TODO cross-compile"

      - if: ${{ startsWith(matrix.platform.os, 'windows-') }}
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            mingw-w64-x86_64-cc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkg-config

      - run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run publish
